export const locationsList = [
    "Acacías",
    "Aguachica",
    "Apartado",
    "Ibagué",
    "Manizales",
    "Mocoa",
    "Villavicencio",
    "Yopal",
    "Pasto",
    "Arauca",
    "Armenia",
    "Barrancabermeja",
    "Barranquilla",
    "Puerto Boyacá",
    "Rioacha",
    "San Andrés",
    "Montelíbano",
    "Montería",
    "Neiva",
    "Barrancas",
    "Buenaventura",
    "Buga",
    "Cali",
    "Tunja",
    "Tulua",
    "Valledupar",
    "Pereira",
    "Popayán",
    "Bucaramanga",
    "Espinal Tolima",
    "Florencia",
    "Girardot",
    "Cartagena",
    "Cúcuta",
    "Duitama",
    "Santa Marta",
    "Sincelejo",
    "Sogamoso"
]